require 'open-uri'

vehicle_1 = URI.open('https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/evoque_d180s_2019_1202a.jpg?itok=B0mfVxHa')
vehicle_2 = URI.open('https://media.wired.com/photos/5d09594a62bcb0c9752779d9/master/pass/Transpo_G70_TA-518126.jpg')
vehicle_3 = URI.open('https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/1-rolls-royce-phantom-2018-review-otr-front.jpg?itok=D66zxiDE')
vehicle_4 = URI.open('https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80')
vehicle_5 = URI.open('https://images.unsplash.com/photo-1532581140115-3e355d1ed1de?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80')
vehicle_6 = URI.open('https://images.unsplash.com/photo-1471289549423-04adaecfa1f1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1906&q=80')
vehicle_7 = URI.open('https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80')
vehicle_8 = URI.open('https://images.unsplash.com/photo-1502877338535-766e1452684a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80')
vehicle_9 = URI.open('https://images.unsplash.com/photo-1527247043589-98e6ac08f56c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80')
vehicle_10 = URI.open('https://images.unsplash.com/photo-1441148345475-03a2e82f9719?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')
vehicle_11 = URI.open('https://images.unsplash.com/photo-1563339007-6914941198b1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80')
vehicle_12 = URI.open('https://images.unsplash.com/photo-1560958089-b8a1929cea89?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80')
vehicle_13 = URI.open('https://images.unsplash.com/photo-1577615765564-4ee327d3fc49?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')
vehicle_14 = URI.open('https://images.unsplash.com/photo-1528501028382-e587fcf3a03e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80')
vehicle_15 = URI.open('https://images.unsplash.com/photo-1504366130991-154787072d46?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1789&q=80')

profile_pic1 = URI.open('https://cdn.guidingtech.com/media/assets/WordPress-Import/2012/10/Smiley-Thumbnail.png')
profile_pic2 = URI.open('https://cdn2.f-cdn.com/contestentries/1376995/30494909/5b5e3e75ab981_thumb900.jpg')
profile_pic3 = URI.open('https://cdn.guidingtech.com/media/assets/WordPress-Import/2012/10/Smiley-Thumbnail.png')

user1 = User.create!(username: "stephanoFW", name: "Stephano", email: "stephanoFW@gmail.com", password:"123456", password_confirmation:"123456")
user1.photo.attach(io: profile_pic1, filename: 'pp1.png', content_type: 'image/png')
car1 = Car.create!(description: "This car is lovely to drive and has all the bells and whistles whilst being eco-friendly and exceptionally cheap to run", price: 160,  year: 2018, doors: 5, transmission: "Manual", seats: 5, model: Faker::Vehicle.model, kind: "Electric", brand: Faker::Vehicle.manufacture, user: user1)
car1.photo.attach(io: vehicle_1, filename: 'vehicle_1.png', content_type: 'image/jpg')
car4 = Car.create!(description: "This vehicle is stunning inside and out, showcasing the most contemporary technology in Audi's tool chest", price: 150, year: 2017, doors: 5, transmission: "Automatic", seats: 5, model: "A8", kind: "Petrol", brand: "Audi", user: user1)
car4.photo.attach(io: vehicle_4, filename: 'vehicle_4.png', content_type: 'image/jpg')
car9 = Car.create!(description: "20in Forged Racing Wheels Matt Black, Adaptive Frontlight System with SBL, Front and rear parking cameras, Passenger display, High power Hi-Fi system, Front Suspension Lift, Carbon fibre driver zone with LEDs, Upper zone in Alcantara, Daytona racing seats", price: 225, year: 2018, doors: 2, transmission: "Automatic", seats: 2, model: " 812 Superfast", kind: "Petrol", brand: "Ferrari", user: user1)
car9.photo.attach(io: vehicle_9, filename: 'vehicle_9.png', content_type: 'image/jpg')
car12 = Car.create!(description: "Dual Motor, Premium Package, Air Suspension, Black Full Leather Interior in Excellent Condition, Four Wheel-Drive, Pearlescent White MultiCoat Finish, 19inch Satin Black Slipstream Wheels in Perfect Condition, Air Suspension, 17in Touchscreen for Media, Communication & Cabin/Vehicle Controls", price: 250,  year: 2018, doors: 5, transmission: "Automatic", seats: 5, model: "Model S", kind: "Electric", brand: "Tesla", user: user1)
car12.photo.attach(io: vehicle_12, filename: 'vehicle_12.png', content_type: 'image/jpg')
car15 = Car.create!(description: "All standard spec plus following extras ,Professional Navigation System, Bluetooth Phone Preparation, 20inch BMW i Turbine Spoke Style 625 Alloy Wheels, Adaptive LED Headlights ,Comfort Access Driving Assistant With Surround View Head-up Display", price: 205, year: 2017, doors: 2, transmission: "Automatic", seats: 4, model: "i8 1.5 7.1kWh Auto", kind: "Hybrid", brand: "BMW", user: user1)
car15.photo.attach(io: vehicle_15, filename: 'vehicle_15.png', content_type: 'image/jpg')

user2 = User.create!(username: "MaxD", name: "Max", email: "max.t.denton@gmail.com", password:"123456", password_confirmation:"123456")
user2.photo.attach(io: profile_pic2, filename: 'pp2.png', content_type: 'image/jpg')
car2 = Car.create!(description: "A fully electric car in mint condition. Rare Signature edition, Full Leather, Bose Sound System, Heated Seats.", price: 170,  year: 2016, doors: 4, transmission: "Automatic", seats: 5, model: Faker::Vehicle.model, kind: "Electric", brand: Faker::Vehicle.manufacture, user: user1)
car2.photo.attach(io: vehicle_2, filename: 'vehicle_2.png', content_type: 'image/jpg')
car5 = Car.create!(description: "Fitted with a wide range of options including Park Assist Front and Rear Sensors with Rear View Camera, Fully Electric heated seats, Transparent Engine Bonnet, and Magneto-Rheologic suspension with lifting system", price: 250,  year: 2018, doors: 2, transmission: "Manual", seats: 2, model: "Aventador", kind: "Diesel", brand: "Lamborghini", user: user1)
car5.photo.attach(io: vehicle_5, filename: 'vehicle_5.png', content_type: 'image/jpg')
car8 = Car.create!(description: "A stunning example in one of the rarest colours- a true eye catcher (Limited edition of 500 cars are the very last of production of this remarkable generation of naturally aspirated v8 M cars", price: 220,  year: 2017, doors: 2, transmission: "Automatic", seats: 4, model: "M3", kind: "Diesel", brand: "BMW", user: user2)
car8.photo.attach(io: vehicle_8, filename: 'vehicle_8.png', content_type: 'image/jpg')
car10 = Car.create!(description: "Finished in Black Sapphire, BMW Navigation, DAB Radio, Bluetooth, Reversing Camera, Sun Protection Glass, Climate Control.", price: 185, year: 2018, doors: 4, transmission: "Automatic", seats: 5, model: "520d M Sport", kind: "Diesel", brand: "BMW", user: user2)
car10.photo.attach(io: vehicle_10, filename: 'vehicle_10.png', content_type: 'image/jpg')
car13 = Car.create!(description: "It’s called the Mercedes-AMG GLE 63 S 4Matic coupé, which is a complicated name for a complicated car combining the high-riding stance of an SUV with the slant-backed profile of a coupé and the engine of a sports car.", price: 200,  year: 2018, doors: 5, transmission: "Manual", seats: 5, model: "GLE63 V8 AMG S (Premium)", kind: "Diesel", brand: "Mercedes-Benz", user: user1)
car13.photo.attach(io: vehicle_13, filename: 'vehicle_13.png', content_type: 'image/jpg')


user3 = User.create!(username: "MaxV", name: "Stephano", email: "max.v@gmail.com", password:"123456", password_confirmation:"123456")
user3.photo.attach(io: profile_pic3, filename: 'pp3.png', content_type: 'image/png')
car3 = Car.create!(description: "Multi purpose car with a range of up to 230 miles. Never have to refill petrol again.", price: 180,  year: 2019, doors: 5, transmission: "Manual", seats: 5, model: Faker::Vehicle.model, kind: "Electric", brand: Faker::Vehicle.manufacture, user: user2)
car3.photo.attach(io: vehicle_3, filename: 'vehicle_3.png', content_type: 'image/jpg')
car6 = Car.create!(description: "Featuring the desired dynamic ride system which along with the 21'' Tri Spoke alloy wheel enhance the handling of this sports tourer.", price: 200,  year: 2019, doors: 2, transmission: "Automatic", seats: 4, model: "Continental", kind: "Diesel", brand: "Bentley", user: user2)
car6.photo.attach(io: vehicle_6, filename: 'vehicle_6.png', content_type: 'image/jpg')
car7 = Car.create!(description: "Panoramic Glass Roof, Sport Chrono Package, Sat Nav, Rear View Camera, Mirrorlink CarPlay, Phone Module, Voice Control, Climate Control, Cruise Control, Electric Heated Memory Seats", price: 200,  year: 2018, doors: 5, transmission: "Automatic", seats: 5, model: "Panamera", kind: "Hybrid", brand: "Porsche", user: user2)
car7.photo.attach(io: vehicle_7, filename: 'vehicle_7.png', content_type: 'image/jpg')
car11 = Car.create!(description: " Audi Phone Box, MMI Navigation Plus, Performance Mode, Parking System Plus, Equipment and Design package and Audi Connect are just some of the most popular and desired features from the specification list that this Audi R8 comes with", price: 220, year: 2017, doors: 2, transmission: "Manual", seats: 2, model: "R8 Rws V10", kind: "Petrol", brand: "Audi", user: user2)
car11.photo.attach(io: vehicle_11, filename: 'vehicle_11.png', content_type: 'image/jpg')
car14 = Car.create!(description: "Carbon fibre engine bay, Glass engine cover, Ceramic brakes, Suspension lift, 20inch Alloys, Front & Side PPF, Reversing camera, Alcantara headlining, Alcantara seat inserts, Alcantara dashboard inserts, Alcantara central armrest, Verde Mantis paintwork with Black half leather/Green alcantara interior", price: 210,  year: 2017, doors: 2, transmission: "Automatic", seats: 2, model: "Huracan V10 LP 610-4", kind: "Petrol", brand: "Lamborghini", user: user2)
car14.photo.attach(io: vehicle_14, filename: 'vehicle_14.png', content_type: 'image/jpg')

booking1 = Booking.create!(car: car1, user: user2, initial_date: DateTime.now, final_date: DateTime.now.to_date, price: 150)
booking2 = Booking.create!(car: car3, user: user1, initial_date: DateTime.now, final_date: DateTime.now.to_date, price: 150)

user4 = User.create!(username: "test", name: "testy", email: "test@test.com", password: "123456", password_confirmation: "123456")
car1.reviews.create!(user: user4, rating: 5, content: 'Pretty damn good')
car2.reviews.create!(user: user4, rating: 4, content: 'Damn good')
car3.reviews.create!(user: user4, rating: 3, content: 'good')
car4.reviews.create!(user: user4, rating: 5, content: 'Lovely car,will book again in future')
car5.reviews.create!(user: user4, rating: 5, content: 'Super fast car')
car6.reviews.create!(user: user4, rating: 4, content: 'Great service,really nice car')
car7.reviews.create!(user: user4, rating: 5, content: 'The car of my dreams,glad i could drive it')
car8.reviews.create!(user: user4, rating: 5, content: 'Awesome car...loved it!')
